export const musicalGenre = [
  {
    id: "Acústico",
    musicalGenre: "Acústico",
  },
  {
    id: "Banda",
    musicalGenre: "Banda",
  },
  {
    id: "Blues",
    musicalGenre: "Blues",
  },
  {
    id: "Clásica",
    musicalGenre: "Clásica",
  },
  {
    id: "Electrónica",
    musicalGenre: "Electrónica",
  },
  {
    id: "Folk",
    musicalGenre: "Folk",
  },
  {
    id: "Jazz",
    musicalGenre: "Jazz",
  },
  {
    id: "Pop",
    musicalGenre: "Pop",
  },
  {
    id: "Rock",
    musicalGenre: "Rock",
  },
  { id: "Salsa", musicalGenre: "Salsa" },
  { id: "Balada", musicalGenre: "Balada" },
  { id: "Tango", musicalGenre: "Tango" },
  { id: "Vallenato", musicalGenre: "Vallenato" },
  { id: "Cumbia", musicalGenre: "Cumbia" },
  { id: "Metal", musicalGenre: "Metal" },
  { id: "Piano", musicalGenre: "Piano" },
  { id: "Regional Mexicano", musicalGenre: "Regional Mexicano" },
  { id: "Saxofón", musicalGenre: "Saxofón" },
  { id: "Tradicional Mexicana", musicalGenre: "Tradicional Mexicana" },
  { id: "Música Urbana", musicalGenre: "Música Urbana" },
  { id: "Bolero", musicalGenre: "Bolero" },
  { id: "Grupero", musicalGenre: "Grupero" },
];

export const typeEvents = [
  { id: "Boda", typeEvents: "Boda" },
  { id: "Cenas", typeEvents: "Cenas" },
  { id: "Concierto en recinto", typeEvents: "Concierto en recinto" },
  { id: "Corporativos", typeEvents: "Corporativos" },
  { id: "Fiestas", typeEvents: "Fiestas" },
  { id: "Servicios Religiosos", typeEvents: "Servicios Religiosos" },
  { id: "Bares", typeEvents: "Bares" },
];

export const MexicanStates = [
  { clave: "Aguascalientes", nombre: "Aguascalientes" },
  { clave: "Baja California", nombre: "Baja California" },
  { clave: "Baja California Sur", nombre: "Baja California Sur" },
  { clave: "Chihuahua", nombre: "Chihuahua" },
  { clave: "Chiapas", nombre: "Chiapas" },
  { clave: "Campeche", nombre: "Campeche" },
  { clave: "Ciudad de México", nombre: "Ciudad de México" },
  { clave: "Coahuila", nombre: "Coahuila" },
  { clave: "Colima", nombre: "Colima" },
  { clave: "Durango", nombre: "Durango" },
  { clave: "Guerrero", nombre: "Guerrero" },
  { clave: "Guanajuato", nombre: "Guanajuato" },
  { clave: "Hidalgo", nombre: "Hidalgo" },
  { clave: "Jalisco", nombre: "Jalisco" },
  { clave: "Michoacán", nombre: "Michoacán" },
  { clave: "Estado de México", nombre: "Estado de México" },
  { clave: "Morelos", nombre: "Morelos" },
  { clave: "Nayarit", nombre: "Nayarit" },
  { clave: "Nuevo León", nombre: "Nuevo León" },
  { clave: "Oaxaca", nombre: "Oaxaca" },
  { clave: "Puebla", nombre: "Puebla" },
  { clave: "Quinta Roo", nombre: "Quinta Roo" },
  { clave: "Queretaro", nombre: "Queretaro" },
  { clave: "Sinaloa", nombre: "Sinaloa" },
  { clave: "San Luis Potosi", nombre: "San Luis Potosi" },
  { clave: "Sonora", nombre: "Sonora" },
  { clave: "Tabasco", nombre: "Tabasco" },
  { clave: "Tlaxcala", nombre: "Tlaxcala" },
  { clave: "Tamaulipas", nombre: "Tamaulipas" },
  { clave: "Veracruz", nombre: "Veracruz" },
  { clave: "Yucatán", nombre: "Yucatán" },
  { clave: "Zacatecas", nombre: "Zacatecas" },
];

export const users = [
  {
    id: 1,
    name: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/1.png",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Zoey Lang",
    role: "Tech Lead",
    team: "Development",
    status: "paused",
    age: "25",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/1.png",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "Jane Fisher",
    role: "Sr. Dev",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/2.png",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "William Howard",
    role: "C.M.",
    team: "Marketing",
    status: "vacation",
    age: "28",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/2.png",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    name: "Kristen Copper",
    role: "S. Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/3.png",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    name: "Brian Kim",
    role: "P. Manager",
    team: "Management",
    age: "29",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/3.png",
    email: "brian.kim@example.com",
    status: "Active",
  },
  {
    id: 7,
    name: "Michael Hunt",
    role: "Designer",
    team: "Design",
    status: "paused",
    age: "27",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/4.png",
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    role: "HR Manager",
    team: "HR",
    status: "active",
    age: "31",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/4.png",
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    name: "Frank Harrison",
    role: "F. Manager",
    team: "Finance",
    status: "vacation",
    age: "33",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/5.png",
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    name: "Emma Adams",
    role: "Ops Manager",
    team: "Operations",
    status: "active",
    age: "35",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/5.png",
    email: "emma.adams@example.com",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    role: "Jr. Dev",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/7.png",
    email: "brandon.stevens@example.com",
  },
  {
    id: 12,
    name: "Megan Richards",
    role: "P. Manager",
    team: "Product",
    status: "paused",
    age: "28",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/7.png",
    email: "megan.richards@example.com",
  },
  {
    id: 13,
    name: "Oliver Scott",
    role: "S. Manager",
    team: "Security",
    status: "active",
    age: "37",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/8.png",
    email: "oliver.scott@example.com",
  },
  {
    id: 14,
    name: "Grace Allen",
    role: "M. Specialist",
    team: "Marketing",
    status: "active",
    age: "30",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/8.png",
    email: "grace.allen@example.com",
  },
  {
    id: 15,
    name: "Noah Carter",
    role: "IT Specialist",
    team: "I. Technology",
    status: "paused",
    age: "31",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/9.png",
    email: "noah.carter@example.com",
  },
  {
    id: 16,
    name: "Ava Perez",
    role: "Manager",
    team: "Sales",
    status: "active",
    age: "29",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/9.png",
    email: "ava.perez@example.com",
  },
  {
    id: 17,
    name: "Liam Johnson",
    role: "Data Analyst",
    team: "Analysis",
    status: "active",
    age: "28",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/11.png",
    email: "liam.johnson@example.com",
  },
  {
    id: 18,
    name: "Sophia Taylor",
    role: "QA Analyst",
    team: "Testing",
    status: "active",
    age: "27",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/11.png",
    email: "sophia.taylor@example.com",
  },
  {
    id: 19,
    name: "Lucas Harris",
    role: "Administrator",
    team: "Information Technology",
    status: "paused",
    age: "32",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/12.png",
    email: "lucas.harris@example.com",
  },
  {
    id: 20,
    name: "Mia Robinson",
    role: "Coordinator",
    team: "Operations",
    status: "active",
    age: "26",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/12.png",
    email: "mia.robinson@example.com",
  },
];
